-- Code generated by dvo xql. DO NOT EDIT.
-- Generated at: 2025-12-28 21:13:42 (ver: 5d1cd5cdc5)

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT PRIMARY KEY,
    account_id BIGINT,
    amount DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    created_by TEXT,
    updated_by TEXT
);
