-- Code generated by dvo xql. DO NOT EDIT.
-- Generated at: 2025-12-28 18:55:38 (ver: 754218eb7f)

CREATE TABLE IF NOT EXISTS accounts (
    id INTEGER PRIMARY KEY,
    email TEXT UNIQUE,
    nick_name varchar(100) NOT NULL UNIQUE DEFAULT 'anonymous',
    category integer DEFAULT 0,
    balance REAL,
    created_at DATETIME,
    updated_at DATETIME,
    created_by TEXT,
    updated_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_accounts_email ON accounts (email);
